defaults:
  - _self_
  - user_settings: user_settings

project_path: ${user_settings.project_path}
datasets_root: ${user_settings.datasets_path}
results_dir: ${user_settings.hydra_dir}
hydra_root: ${user_settings.hydra_root}
hydra_dir: ${user_settings.hydra_dir}
hydra:
  run:
    dir: ${hydra_dir}

data_dir: ${datasets_root}/data
location: ${data_dir}/iam
words_path: &wp ${location}/words
labels_file: &lf ${location}/words.txt
output_path: &op ${data_dir}/output
processed_words_path: &pwp ${output_path}/words
err_words_path: &ewp ${output_path}/words_with_error

models_output: ${project_path}/models

save_image_dir: &sid ${user_settings.results_dir}/test_image
image_name: &in test_image.png

data_loader:
  _target_: src.dataloader.dataloader.Loader
  prohibited:
   - ','
   - '('
   - ')'
   - ';'
   - ':'
   - '/'
   - '\\'
   - '#'
   - '"'
   - '?'
   - '!'
   - '*'
   - '_'
   - '&'
  words_path: *wp
  labels_file: *lf
  output_path: *op
  processed_words_path: *pwp
  err_words_path: *ewp

painter:
  _target_: src.utils.painter.Painter
  save_root: *sid
  image_name: *in
  canvas_width: 1000
  canvas_height: 600
  default_size: 4
  default_color: black

# --------------------------
train_steps: 1000000
save_iter: 2000
batch_size: 64

params:
  available_writers: 672
  results_file: ${datasets_root}/results/results.txt
  time_file: ${datasets_root}/results/time.txt'
  feature_extraction_method: overlapping # lines overlapping
  classifier: support_vector # neural_network support_vector
  histogram_bins: 256
  nn_learning_rate: 0.003
  nn_weight_decay: 0.01
  nn_dropout: 0.25
  nn_epochs: 200
  nn_batch_size: 16
