defaults:
  - _self_
  - user_settings: user_settings

project_path: ${user_settings.project_path}
datasets_root: ${user_settings.datasets_path}
results_dir: ${user_settings.hydra_dir}
hydra_root: ${user_settings.hydra_root}
hydra_dir: ${user_settings.hydra_dir}
hydra:
  run:
    dir: ${hydra_dir}

data_dir: ${datasets_root}/data
location: ${data_dir}/iam
words_path: &wp ${location}/words
labels_file: &lf ${location}/words.txt
output_path: &op ${data_dir}/output
processed_words_path: &pwp ${output_path}/words
err_words_path: &ewp ${output_path}/words_with_error

csv_path: ${data_dir}/sets
models_output: ${project_path}/models

save_image_dir: &sid ${user_settings.results_dir}/test_image
image_name: &in test_image.png

data_loader:
  _target_: src.dataloader.dataloader.Loader
  prohibited:
   - ','
   - '('
   - ')'
   - ';'
   - ':'
   - '/'
   - '\\'
   - '#'
   - '"'
   - '?'
   - '!'
   - '*'
   - '_'
   - '&'
  words_path: *wp
  labels_file: *lf
  output_path: *op
  processed_words_path: *pwp
  err_words_path: *ewp

test_set: 0.1
validation_set: 0.1

model_params:
  layers: 2
  residual_layers: 0
  units: 512
  num_buckets: 10
  learning_rate: 1e-4
  dropout: 0.4
  train_steps: 20000
  test_iter: 150
  save_iter: 500
  epoch: 500
  batch_size: 64
  model_name: WordPredictor
  scale: 0.0003
  hn_pool: 16  # 2^(number of pooling layers on height)
  wn_pool: 8  # 2^(number of pooling layers on width)

painter:
  _target_: src.utils.painter.Painter
  save_root: *sid
  image_name: *in
  canvas_width: 1000
  canvas_height: 600
  default_size: 4
  default_color: black
